README.md

frontend setup instructions (& PR note)

---

backend/api.py
backend/init_db.py

Add sample data to DB, make flask return it

---

one-step-build.sh

It's cleaner and I have ran into issues with the old way (the OR: ||)

1-step build: use if-statements

---

backend/testing.py

Create testing framework

---

backend/api.py
backend/init_db.py
backend/models.py

add user to user table

---

README.md
dev-setup-script.sh

dev setup script

---

backend/api.py
backend/init_db.py
backend/models.py

I created a model for a closet  and then related the items together.

Add clothing item

---

backend/api.py
backend/init_db.py
backend/models.py
my-app/package-lock.json
my-app/package.json
my-app/src/component/Drawer.js
my-app/src/component/Header.js
my-app/src/pages/closet.js
my-app/src/pages/home.js

Goes back to 78ff9d3d50f5a54124c264dc0e4ee1fef4a5b15b

Undo accidenal merges

---

my-app/src/pages/home.js

Force User to enter number

---

my-app/src/component/Header.js
my-app/src/index.js
my-app/src/pages/closet.js

If user refreshes page, redirect to login screen

---

backend/api.py
backend/init_db.py
backend/models.py
backend/testing.py
backend/w2w_logic/outfit_generator.py

Generate outfit endpoint (& fix init_db + tests)

---

backend/init_db.py
backend/w2w_logic/outfit_generator.py

Modify default sample data (snowy + rainy)

---

backend/api.py
backend/init_db.py
backend/models.py
backend/testing.py
backend/w2w_logic/outfit_generator.py
backend/weather.py
my-app/src/component/Drawer.js
my-app/src/component/Header.js

Code cleanup: Linting + remove unused endpoint 

---

backend/api.py
backend/init_db.py
backend/models.py
backend/testing.py
backend/w2w_logic/outfit_generator.py
backend/weather.py
my-app/src/component/Drawer.js
my-app/src/component/Header.js
my-app/src/pages/closet.js

Allow creating new tags/attributes in frontend

---

my-app/src/component/ClothingItem.js
my-app/src/helpers.js
my-app/src/pages/closet.js

Draft - awaiting backend support

Edit item and delete item buttons + functionality

---

backend/weather.py
my-app/src/component/Outfit.js
my-app/src/component/WeatherDashboard.js
my-app/src/pages/HomeDashboard.js

Regenerate Outfit Functionality

---

backend/api.py
backend/init_db.py
backend/models.py
my-app/package-lock.json
my-app/src/component/Drawer.js
my-app/src/component/Outfit.js
my-app/src/component/OutfitTemplateForm.js
my-app/src/pages/HomeDashboard.js
my-app/src/pages/closet.js

W2w presentation

---

my-app/src/component/Outfit.js

Fix hardcoded user when regening item

---

backend/api.py
my-app/src/component/ClothingItem.js

Fix edit item

---

my-app/src/component/Outfit.js
my-app/src/pages/HomeDashboard.js

Return outfitTemplate picker, manually merged 'HomeDashboard'
